In [1]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from IPython.display import HTML

from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [3]:
IMAGE_SIZE = 256
CHANNELS = 3

train_datagen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    rotation_range=10
)

train_generator = train_datagen.flow_from_directory(
    'dataset/train',
    target_size=(IMAGE_SIZE,IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse'
)

Found 14440 images belonging to 15 classes.


In [5]:
for image_batch, label_batch in train_generator:
    print(image_batch[0])
    break

[[[0.691745   0.6172352  0.6250783 ]
  [0.6897121  0.6152023  0.62304544]
  [0.6876792  0.6131694  0.6210125 ]
  ...
  [0.7378971  0.6673088  0.6673088 ]
  [0.73976    0.6691717  0.6691717 ]
  [0.7537404  0.68315214 0.68315214]]

 [[0.70498407 0.6304742  0.63831735]
  [0.7034594  0.6289495  0.63679266]
  [0.70193475 0.62742496 0.6352681 ]
  ...
  [0.73688066 0.6662924  0.6662924 ]
  [0.74179286 0.6712046  0.6712046 ]
  [0.75526506 0.6846768  0.6846768 ]]

 [[0.7075221  0.6330123  0.64085543]
  [0.70803034 0.63352054 0.6413637 ]
  [0.70853853 0.63402873 0.64187187]
  ...
  [0.73586416 0.66527593 0.66527593]
  [0.7438257  0.67323744 0.67323744]
  [0.7567897  0.68620145 0.68620145]]

 ...

 [[0.5594528  0.43788415 0.43004102]
  [0.5568628  0.43529415 0.427451  ]
  [0.5581282  0.43655956 0.42871642]
  ...
  [0.5676127  0.44996566 0.44212252]
  [0.56405514 0.4464081  0.43856496]
  [0.5604976  0.44285056 0.43500742]]

 [[0.5589446  0.43737593 0.4295328 ]
  [0.5568628  0.43529415 0.427451  ]


In [6]:
validation_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,
    horizontal_flip=True
)
validation_generator = validation_datagen.flow_from_directory(
    'dataset/val',
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=32,
    class_mode="sparse"
)

Found 2058 images belonging to 15 classes.


In [7]:
test_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,
    horizontal_flip=True
)
test_generator = validation_datagen.flow_from_directory(
    'dataset/test',
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=32,
    class_mode="sparse"
)

Found 4140 images belonging to 15 classes.


In [9]:
input_shape= (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
n_classes = 15

model = models.Sequential([
    layers.InputLayer(input_shape=input_shape),
    layers.Conv2D(32, kernel_size=(3,3), activation='relu', input_shape = input_shape),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    
    layers.Flatten(),
    layers.Dense(64,activation='relu'),
    layers.Dense(n_classes, activation='softmax'),
])

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 254, 254, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 127, 127, 32)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 125, 125, 64)      18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 62, 62, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 60, 60, 64)        36928     
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 30, 30, 64)       0

In [16]:
#now compiling the model

model.compile(
    optimizer = 'adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

In [19]:
#14440/32

#2058/32



64.3125

In [ ]:
# history = model.fit(
#     train_generator,
#     steps_per_epoch=451,
#     batch_size=32,
#     validation_data = validation_generator,
#     validation_steps = 64,
#     verbose=1,
#     epochs=30
# )

Epoch 1/30
118/451 [======>.......................] - ETA: 10:06 - loss: 2.2975 - accuracy: 0.2375